name: MyPy

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"
      target-path:
        required: false
        type: string
        default: "."

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-interaction --no-ansi

      - name: Run MyPy
        run: |
          poetry run mypy ${{ inputs.target-path }}
