name: Pylint

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"
      target-path:
        required: false
        type: string
        default: "."
      package-name:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-interaction --no-ansi

      - name: Run pytest with coverage
        run: |
          poetry run pytest --cov=${{ inputs.package-name }} --cov-report=html --cov-report=term-missing

      - name: Upload coverage HTML report
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-html-report
          path: htmlcov/
